### ISSUE TITLE
Package information

### ISSUE THREAD

**Issue by tashbettridge** [gottagetgit/AI102Files#1]
Hi, 
I would appreciate any advice - I was wondering what packages you pre-installed on py charm when you ran the Computer Vision Module for Retrieve Image Description.py. I am getting some unresolved reference errors and it is trying to correct computer vision. Please see screenshot below. I know this is probably a user error so any advice is much appreciated. 

![image](https://user-images.githubusercontent.com/32854599/121762826-7abd0500-cb8c-11eb-8d07-e8a403cdc0c8.png)

**Comment by Jordinthecloud** [comment]
@ciph3rwoman: 

From the Pycharm terminal you need to install the "azure-cognitiveservices-vision-computervision" SDK for that:

`pip install azure-cognitiveservices-vision-computervision`
